<a href="https://colab.research.google.com/github/amitverma7426/DataScience/blob/main/Final_Project_Classification_with_Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Surpress warnings:
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn

In [2]:
#you are running the lab in your  browser, so we will install the libraries using ``piplite``
import piplite
await piplite.install(['pandas'])
await piplite.install(['numpy'])

ModuleNotFoundError: No module named 'piplite'

In [17]:
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.linear_model import LinearRegression
from sklearn import preprocessing
import numpy as np
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn import svm
from sklearn.metrics import jaccard_score
from sklearn.metrics import f1_score
from sklearn.metrics import log_loss
from sklearn.metrics import confusion_matrix, accuracy_score
import sklearn.metrics as metrics

In [31]:
path='https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillUp/labs/ML-FinalAssignment/Weather_Data.csv'

In [32]:
df = pd.read_csv(path)
df.head()

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine WindGustDir  \
0  2/1/2008     19.5     22.4      15.6          6.2       0.0           W   
1  2/2/2008     19.5     25.6       6.0          3.4       2.7           W   
2  2/3/2008     21.6     24.5       6.6          2.4       0.1           W   
3  2/4/2008     20.2     22.8      18.8          2.2       0.0           W   
4  2/5/2008     19.7     25.7      77.4          4.8       0.0           W   

   WindGustSpeed WindDir9am WindDir3pm  ...  Humidity9am  Humidity3pm  \
0             41          S        SSW  ...           92           84   
1             41          W          E  ...           83           73   
2             41        ESE        ESE  ...           88           86   
3             41        NNE          E  ...           83           90   
4             41        NNE          W  ...           88           74   

   Pressure9am  Pressure3pm  Cloud9am  Cloud3pm  Temp9am  Temp3pm  RainToday  \
0       1017.6       1017.4         8         8     20.7     20.9        Yes   
1       1017.9       1016.4         7         7     22.4     24.8        Yes   
2       1016.7       1015.6         7         8     23.5     23.0        Yes   
3       1014.2       1011.8         8         8     21.4     20.9        Yes   
4       1008.3       1004.8         8         8     22.5     25.5        Yes   

   RainTomorrow  
0           Yes  
1           Yes  
2           Yes  
3           Yes  
4           Yes  

[5 rows x 22 columns]


1.Data prepocesssion

In [33]:
 df_sydney_processed = pd.get_dummies(data=df, columns=['RainToday', 'WindGustDir', 'WindDir9am', 'WindDir3pm'])
df_sydney_processed

Date  MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  \
0      2/1/2008     19.5     22.4      15.6          6.2       0.0   
1      2/2/2008     19.5     25.6       6.0          3.4       2.7   
2      2/3/2008     21.6     24.5       6.6          2.4       0.1   
3      2/4/2008     20.2     22.8      18.8          2.2       0.0   
4      2/5/2008     19.7     25.7      77.4          4.8       0.0   
...         ...      ...      ...       ...          ...       ...   
3266  6/21/2017      8.6     19.6       0.0          2.0       7.8   
3267  6/22/2017      9.3     19.2       0.0          2.0       9.2   
3268  6/23/2017      9.4     17.7       0.0          2.4       2.7   
3269  6/24/2017     10.1     19.3       0.0          1.4       9.3   
3270  6/25/2017      7.6     19.3       0.0          3.4       9.4   

      WindGustSpeed  WindSpeed9am  WindSpeed3pm  Humidity9am  ...  \
0                41            17            20           92  ...   
1                41             9            13           83  ...   
2                41            17             2           88  ...   
3                41            22            20           83  ...   
4                41            11             6           88  ...   
...             ...           ...           ...          ...  ...   
3266             37            22            20           73  ...   
3267             30            20             7           78  ...   
3268             24            15            13           85  ...   
3269             43            17            19           56  ...   
3270             35            13            13           73  ...   

      WindDir3pm_NNW  WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  \
0              False          False         False          False   
1              False          False         False          False   
2              False          False         False          False   
3              False          False         False          False   
4              False          False         False          False   
...              ...            ...           ...            ...   
3266           False          False         False          False   
3267           False          False         False          False   
3268           False          False         False          False   
3269           False          False         False          False   
3270           False          False         False          False   

      WindDir3pm_SSE  WindDir3pm_SSW  WindDir3pm_SW WindDir3pm_W  \
0              False            True          False        False   
1              False           False          False        False   
2              False           False          False        False   
3              False           False          False        False   
4              False           False          False         True   
...              ...             ...            ...          ...   
3266            True           False          False        False   
3267           False           False          False        False   
3268           False           False          False        False   
3269           False           False          False         True   
3270           False           False          False         True   

      WindDir3pm_WNW  WindDir3pm_WSW  
0              False           False  
1              False           False  
2              False           False  
3              False           False  
4              False           False  
...              ...             ...  
3266           False           False  
3267           False           False  
3268           False           False  
3269           False           False  
3270           False           False  

[3271 rows x 68 columns]

In [34]:
df.columns

Index(['Date', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [22]:
# Change df.columns() to df.columns
df.columns

Index(['Date', 'MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RainTomorrow'],
      dtype='object')

In [35]:
  df_sydney_processed.replace(['No', 'Yes'], [0,1], inplace=True)




2. Training Data and Test Data



In [36]:
df_sydney_processed.drop('Date',axis=1,inplace=True)

In [37]:
df_sydney_processed = df_sydney_processed.astype(float)
df_sydney_processed

MinTemp  MaxTemp  Rainfall  Evaporation  Sunshine  WindGustSpeed  \
0        19.5     22.4      15.6          6.2       0.0           41.0   
1        19.5     25.6       6.0          3.4       2.7           41.0   
2        21.6     24.5       6.6          2.4       0.1           41.0   
3        20.2     22.8      18.8          2.2       0.0           41.0   
4        19.7     25.7      77.4          4.8       0.0           41.0   
...       ...      ...       ...          ...       ...            ...   
3266      8.6     19.6       0.0          2.0       7.8           37.0   
3267      9.3     19.2       0.0          2.0       9.2           30.0   
3268      9.4     17.7       0.0          2.4       2.7           24.0   
3269     10.1     19.3       0.0          1.4       9.3           43.0   
3270      7.6     19.3       0.0          3.4       9.4           35.0   

      WindSpeed9am  WindSpeed3pm  Humidity9am  Humidity3pm  ...  \
0             17.0          20.0         92.0         84.0  ...   
1              9.0          13.0         83.0         73.0  ...   
2             17.0           2.0         88.0         86.0  ...   
3             22.0          20.0         83.0         90.0  ...   
4             11.0           6.0         88.0         74.0  ...   
...            ...           ...          ...          ...  ...   
3266          22.0          20.0         73.0         52.0  ...   
3267          20.0           7.0         78.0         53.0  ...   
3268          15.0          13.0         85.0         56.0  ...   
3269          17.0          19.0         56.0         35.0  ...   
3270          13.0          13.0         73.0         32.0  ...   

      WindDir3pm_NNW  WindDir3pm_NW  WindDir3pm_S  WindDir3pm_SE  \
0                0.0            0.0           0.0            0.0   
1                0.0            0.0           0.0            0.0   
2                0.0            0.0           0.0            0.0   
3                0.0            0.0           0.0            0.0   
4                0.0            0.0           0.0            0.0   
...              ...            ...           ...            ...   
3266             0.0            0.0           0.0            0.0   
3267             0.0            0.0           0.0            0.0   
3268             0.0            0.0           0.0            0.0   
3269             0.0            0.0           0.0            0.0   
3270             0.0            0.0           0.0            0.0   

      WindDir3pm_SSE  WindDir3pm_SSW  WindDir3pm_SW  WindDir3pm_W  \
0                0.0             1.0            0.0           0.0   
1                0.0             0.0            0.0           0.0   
2                0.0             0.0            0.0           0.0   
3                0.0             0.0            0.0           0.0   
4                0.0             0.0            0.0           1.0   
...              ...             ...            ...           ...   
3266             1.0             0.0            0.0           0.0   
3267             0.0             0.0            0.0           0.0   
3268             0.0             0.0            0.0           0.0   
3269             0.0             0.0            0.0           1.0   
3270             0.0             0.0            0.0           1.0   

      WindDir3pm_WNW  WindDir3pm_WSW  
0                0.0             0.0  
1                0.0             0.0  
2                0.0             0.0  
3                0.0             0.0  
4                0.0             0.0  
...              ...             ...  
3266             0.0             0.0  
3267             0.0             0.0  
3268             0.0             0.0  
3269             0.0             0.0  
3270             0.0             0.0  

[3271 rows x 67 columns]

In [38]:
X = df_sydney_processed.drop(columns='RainTomorrow', axis=1)
Y = df_sydney_processed['RainTomorrow']



3. Linear Regression



In [39]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=10)

In [40]:
LinearReg = LinearRegression()
LinearReg.fit(X_train, Y_train)

LinearRegression()

In [41]:
predictions = LinearReg.predict(X_test)
predictions

array([ 1.31546021e-01,  2.76123047e-01,  9.78118896e-01,  2.87567139e-01,
        1.32431030e-01,  4.60571289e-01,  3.56704712e-01,  8.56384277e-01,
        6.75079346e-01,  3.82385254e-02,  4.85229492e-03,  2.81097412e-01,
        3.39157104e-01,  7.79113770e-02,  6.26525879e-02,  5.64575195e-01,
       -6.15539551e-02,  5.24200439e-01,  1.53778076e-01,  3.59802246e-01,
        6.04705811e-02,  9.03701782e-01,  4.67239380e-01,  2.03430176e-01,
       -7.11669922e-02,  3.83895874e-01,  5.36193848e-01, -2.29187012e-02,
        6.39862061e-01, -9.59320068e-02,  3.77960205e-01,  1.20300293e-01,
       -1.81732178e-02,  5.53131104e-02,  5.63537598e-01,  1.06314087e+00,
       -6.79016113e-03,  5.14434814e-01, -8.83331299e-02,  6.91833496e-02,
        2.45056152e-02,  8.71856689e-01,  2.44674683e-01,  3.94897461e-01,
        2.67486572e-01,  4.46868896e-01, -4.75463867e-02,  1.89315796e-01,
        7.76901245e-01,  1.57638550e-01,  3.60107422e-03, -5.19409180e-02,
        2.07504272e-01, -

In [44]:
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

# Calculate Mean Absolute Error
LinearRegression_MAE = mean_absolute_error(Y_test, predictions)

# Calculate Mean Squared Error
LinearRegression_MSE = mean_squared_error(Y_test, predictions)

# Calculate R-squared
LinearRegression_R2 = r2_score(Y_test, predictions)

# Print the calculated metrics
print("Linear Regression Metrics:")
print("Mean Absolute Error:", LinearRegression_MAE)
print("Mean Squared Error:", LinearRegression_MSE)
print("R-squared:", LinearRegression_R2)


Linear Regression Metrics:
Mean Absolute Error: 0.2563092413749404
Mean Squared Error: 0.11571947414932758
R-squared: 0.42713759580777166


In [45]:
# Create a DataFrame to store the metrics
Report = pd.DataFrame({
    'Metric': ['Mean Absolute Error (MAE)', 'Mean Squared Error (MSE)', 'R-squared (R2)'],
    'Value': [LinearRegression_MAE, LinearRegression_MSE, LinearRegression_R2]
})

# Display the DataFrame
print("Linear Regression Metrics:")
print(Report)

Linear Regression Metrics:
                      Metric     Value
0  Mean Absolute Error (MAE)  0.256309
1   Mean Squared Error (MSE)  0.115719
2             R-squared (R2)  0.427138


In [46]:
Report

Metric     Value
0  Mean Absolute Error (MAE)  0.256309
1   Mean Squared Error (MSE)  0.115719
2             R-squared (R2)  0.427138

In [47]:
KNN = KNeighborsClassifier(n_neighbors=4)
KNN.fit(X_train, Y_train)

KNeighborsClassifier(n_neighbors=4)

In [48]:
predictions = KNN.predict(X_test)
predictions

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 0.

In [ ]:
#KNN_Accuracy_Score =
#KNN_JaccardIndex =
#KNN_F1_Score =

In [51]:
from sklearn import metrics
KNN_Accuracy_Score = metrics.accuracy_score(Y_test, predictions)
KNN_JaccardIndex = metrics.jaccard_score(Y_test, predictions)
KNN_F1_Score = metrics.f1_score(Y_test, predictions)
print("KNN Accuracy Score:", KNN_Accuracy_Score)
print("KNN Jaccard Index:", KNN_JaccardIndex)
print("KNN F1 Score:", KNN_F1_Score)

KNN Accuracy Score: 0.8183206106870229
KNN Jaccard Index: 0.4251207729468599
KNN F1 Score: 0.5966101694915255


In [59]:
# Create a DataFrame to store the metrics
Report2 = pd.DataFrame({
    'Metric': ['KNN Accuracy Score', 'KNN Jaccard Index', 'KNN F1 Score'],
    'Value': [KNN_Accuracy_Score, KNN_JaccardIndex, KNN_F1_Score]
})
Report2

Metric     Value
0  KNN Accuracy Score  0.818321
1   KNN Jaccard Index  0.425121
2        KNN F1 Score  0.596610

In [53]:
Tree = DecisionTreeClassifier(criterion="entropy", max_depth = 4)
Tree.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [54]:
Tree.fit(X_train, Y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=4)

In [55]:
predictions = Tree.predict(X_test)
predictions

array([0., 0., 1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 0., 0., 1., 0., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0.,
       0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 0., 1., 1., 0., 0., 1., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1., 0., 0., 0., 0.,
       1., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 0., 0.

In [ ]:
#Tree_Accuracy_Score =
#Tree_JaccardIndex =
#Tree_F1_Score =

In [60]:
from sklearn import metrics
tree_accuracy = metrics.accuracy_score(Y_test, predictions)
tree_jaccard_index = metrics.jaccard_score(Y_test, predictions)
tree_f1_score = metrics.f1_score(Y_test, predictions)
print("Decision Tree Accuracy Score:", tree_accuracy)
print("Decision Tree Jaccard Index:", tree_jaccard_index)
print("Decision Tree F1 Score:", tree_f1_score)

Decision Tree Accuracy Score: 0.8183206106870229
Decision Tree Jaccard Index: 0.48034934497816595
Decision Tree F1 Score: 0.6489675516224188


In [61]:
# Create a DataFrame to store the metrics
Report3 = pd.DataFrame({
    'Metric': ['Decision Tree Accuracy Score', 'Decision Tree Jaccard Index', 'Decision Tree F1 Score'],
    'Value': [ tree_accuracy, tree_jaccard_index, tree_f1_score]
})
Report3

Metric     Value
0  Decision Tree Accuracy Score  0.818321
1   Decision Tree Jaccard Index  0.480349
2        Decision Tree F1 Score  0.648968



4.**Logistic** **Regression**



In [62]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, random_state=1)

In [63]:
LR = LogisticRegression(C=0.01, solver='liblinear').fit(X_train,Y_train)
LR

LogisticRegression(C=0.01, solver='liblinear')

In [64]:
predictions = LR.predict(X_test)
predictions

array([0., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1.,
       0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1.,
       1., 1., 1., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 1.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1.,
       0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.,
       0., 0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 0., 1.,
       0., 0., 1., 0., 0., 1., 0., 1., 0., 1., 1., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
       0., 1., 1., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.,
       1., 0., 1., 1., 0.

In [65]:
predict_proba = LR.predict_proba(X_test)
predict_proba

array([[0.71865883, 0.28134117],
       [0.9758831 , 0.0241169 ],
       [0.49701317, 0.50298683],
       ...,
       [0.97264179, 0.02735821],
       [0.7334115 , 0.2665885 ],
       [0.3853586 , 0.6146414 ]])

In [ ]:
#LR_Accuracy_Score =
#LR_JaccardIndex =
#LR_F1_Score =
#LR_Log_Loss =

In [69]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score, log_loss
LR_Accuracy_Score = accuracy_score(Y_test, predictions,)
LR_JaccardIndex = jaccard_score(Y_test, predictions)
LR_F1_Score = f1_score(Y_test, predictions)
LR_Log_Loss = log_loss(Y_test, predict_proba)
print("Logistic Regression Accuracy Score:", LR_Accuracy_Score)
print("Logistic Regression Jaccard Index:", LR_JaccardIndex)
print("Logistic Regression F1 Score:", LR_F1_Score)
print("Logistic Regression Log Loss:", LR_Log_Loss)

Logistic Regression Accuracy Score: 0.8274809160305343
Logistic Regression Jaccard Index: 0.4840182648401826
Logistic Regression F1 Score: 0.6523076923076923
Logistic Regression Log Loss: 0.38008468000382284


In [82]:
# Create a DataFrame to store the metrics
Report4 = pd.DataFrame({
    'Metric': ['Logistic Regression Accuracy Score', 'Logistic Regression Jaccard Index', 'Logistic Regression F1 Score', 'Logistic Regression Log Loss'],
    'Value': [  LR_Accuracy_Score, LR_JaccardIndex,  LR_F1_Score,LR_Log_Loss ]
})
Report4

Metric     Value
0  Logistic Regression Accuracy Score  0.827481
1   Logistic Regression Jaccard Index  0.484018
2        Logistic Regression F1 Score  0.652308
3        Logistic Regression Log Loss  0.380085



5. SVM



In [72]:
SVM = svm.SVC(kernel='rbf')
SVM.fit(X_train, Y_train)

SVC()

In [73]:
predictions = SVM.predict(X_test)
predictions

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [ ]:
#SVM_Accuracy_Score =
#SVM_JaccardIndex =
#SVM_F1_Score =

In [83]:
from sklearn.metrics import accuracy_score, jaccard_score, f1_score
svm_accuracy = accuracy_score(Y_test, predictions)
svm_jaccard_index = jaccard_score(Y_test, predictions)
svm_f1_score = f1_score(Y_test, predictions)
print("SVM Accuracy Score:", svm_accuracy)
print("SVM Jaccard Index:", svm_jaccard_index)
print("SVM F1 Score:", svm_f1_score)


SVM Accuracy Score: 0.7221374045801526
SVM Jaccard Index: 0.0
SVM F1 Score: 0.0


In [86]:
# Create a DataFrame to store the metrics
Report5 = pd.DataFrame({
    'Metric': ['SVM Accuracy Score', 'SVM Jaccard Index', 'SVM F1 Score'],
    'Value': [svm_accuracy, svm_jaccard_index, svm_f1_score]
})
Report5

Metric     Value
0  SVM Accuracy Score  0.722137
1   SVM Jaccard Index  0.000000
2        SVM F1 Score  0.000000